name: CI

on:
  push:
    branches: [ "main" ]

jobs:
#  laravel-tests:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
#        with:
#          php-version: '8.2'
#      - uses: actions/checkout@v4
#      - name: Copy .env
#        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
#      - name: Install Dependencies
#        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#      - name: Generate key
#        run: php artisan key:generate
#      - name: Directory Permissions
#        run: chmod -R 777 storage bootstrap/cache
#      - name: Create Database
#        run: |
#          mkdir -p database
#          touch database/database.sqlite
#      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
#        env:
#          DB_CONNECTION: sqlite
#          DB_DATABASE: database/database.sqlite
#        run: php artisan test
  build:
    runs-on: ubuntu-latest
#    needs: laravel-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          file: ./docker/php/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/laravel-docker:latest
            ghcr.io/${{ github.repository_owner }}/laravel-docker:${{ github.run_number }}

  push-image-tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
      - name: Save run number to file
        run: echo "${{ github.run_number }}" > image-run.yaml
      - name: Clone target repository
        run: |
          git clone https://x-access-token:${{ secrets.API_TOKEN_GITHUB }}@github.com/axyr/laravel-kubernetes-examples target-repo
          cd target-repo
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      - name: Copy run number
        run: cp image-run.yaml target-repo/kubernetes/laravel-single-pod
      - name: Commit and push changes
        run: |
          cd target-repo
          git add kubernetes/laravel-single-pod/image-run.yaml
          git commit -m "Update run number: ${{ github.run_number }}"
          git push --force
